# This is a basic workflow to help you get started with Actions

name: Deploy to Ec2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    # GitHub Actions에서 EC2 SSH 접속 후 명령어를 실행할 수 있게 해준다.
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env,docker-compose.yml"
          target: "/home/ubunt/infra-server"
          script: |
            cd /home/ubuntu/infra-server
            docker compose pull
            docker compose up -d
